# ========================================
# Date: 09.09.2025
# Author: @joaoasantana
# =========================================
---
include:
  - board: nice_nano_v2
    shield: corne_left nice_oled
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"JV_Corne_OLED\"
    artifact-name: nice_corne_left_oled
    snippet: studio-rpc-usb-uart
    
  - board: nice_nano_v2
    shield: corne_right nice_oled
    artifact-name: nice_corne_right_oled

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_settings_reset
